version: '3.1'
services:

    db:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        volumes:
            - /data/mysql:/var/lib/mysql
        environment:
            MYSQL_DATABASE: wordpress
            MYSQL_ROOT_PASSWORD: WordPress@2021

    adminer:
        image: adminer
        restart: always
        ports:
            - 10086:8080

    wordpress:
        image: hongwenjun/nginx-php
        container_name: wordpress
        restart: always
        volumes:
            - /data/www/wordpress:/var/www/html
        ports:
            - 80:80
            - 443:443
