FROM debian:stable-slim
RUN  apt update -y \
  && apt install --no-install-recommends --no-install-suggests -y wget unzip python3 python3-pip \
  && wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb \
  && dpkg -i google-chrome-stable_current_amd64.deb ; apt-get -f -y --no-install-recommends --no-install-suggests install \
  && dpkg -i google-chrome-stable_current_amd64.deb  \
  && rm google-chrome-stable_current_amd64.deb  \
  && wget https://chromedriver.storage.googleapis.com/92.0.4515.107/chromedriver_linux64.zip \
  && unzip chromedriver_linux64.zip  \
  && rm chromedriver_linux64.zip  \
  && mv chromedriver /usr/bin/chromedriver  \
  && apt-get clean  \
  && apt-get autoremove  \
  && rm -rf /var/lib/apt/lists/*  \
  && pip3 install selenium
  
#  docker build  -t chrome  -f Dockerfile-Chrome-Selenium  .

#  docker run -d  --restart=always -v /app:/app --name chrome chrome python3 -m http.server
