name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run:  echo ${{ secrets.GITHUB_TOKEN }}  | docker login https://docker.pkg.github.com -u hongwenjun --password-stdin  && \
            echo  "测试 docker login "  && docker buildx ls
