name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker buildx . --file Dockerfile --tag hongwenjun/nginx-php:$(date +%s) \
              --platform=linux/arm,linux/arm64,linux/amd64  --push
